; Extra options:
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1] ; Change this to env:esp32-s3 on flight computer
platform = espressif32
board = esp32-s3-devkitc-1 ; Change this to esp32-s3 on flight computer
framework = arduino
monitor_speed = 115200

; Set these flags to display USB output
build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D CORE_DEBUG_LEVEL=5